#!/bin/bash
# SPDX-FileCopyrightText: 2026 Komiya Takumi
# SPDX-License-Identifier: BSD-3-Clause

if [ -t 0 ]; then
  echo "Usage: echo 都道府県名 | pref2region" >&2
  exit 1
fi

DATA="$(dirname "$0")/prefectures.txt"

awk -v data="$DATA" '
BEGIN {
  while ((getline < data) > 0) {
    region[$1] = $2
    capital[$1] = $3
  }
}
{
  if ($1 in region) {
    print region[$1], capital[$1]
  } else {
    print "Unknown prefecture: " $1 > "/dev/stderr"
    exit 1
  }
}
'
